import { routing } from "../i18n/routing.ts";

// Hand-maintained rename map. Originally generated by the one-shot rename in
// commit 8655f8b (2026-09-01); the old slugs no longer exist on disk, so this
// map cannot be re-derived and is the source of truth for the 308s.
// Every entry must keep passing command-post/slug_guard.py (R4 derives the
// expected renames from git history). Slug judgment: the `slug-naming` skill.
export const SLUG_RENAMES: Readonly<Record<string, string>> = {
  "asheville-north-carolina-vacation-guide-2026": "asheville-north-carolina-vacation-guide",
  "best-cruise-itineraries-fort-lauderdale-miami-2026": "best-cruise-itineraries-fort-lauderdale-miami",
  "big-sky-mt-vacation-guide-2026": "big-sky-mt-vacation-guide",
  "boston-weekend-getaway-guide-2026": "boston-weekend-getaway-guide",
  "cape-cod-vacation-guide-2026": "cape-cod-vacation-guide",
  "caribbean-cruise-itineraries-2026": "caribbean-cruise-itineraries",
  "charleston-coast-vacation-guide-2026": "charleston-coast-vacation-guide",
  "florida-travel-guide-2019": "florida-travel-guide",
  "fort-walton-beach-vacation-guide-2026": "fort-walton-beach-vacation-guide",
  "hawaii-vacation-planning-guide-2026": "hawaii-vacation-planning-guide",
  "hilton-head-vacation-guide-2026": "hilton-head-vacation-guide",
  "key-west-florida-vacation-guide-2026": "key-west-florida-vacation-guide",
  "lake-tahoe-vacation-guide-2026": "lake-tahoe-vacation-guide",
  "mexico-vacation-guide-2026": "mexico-vacation-guide",
  "miramar-rosemary-beach-vacation-guide-2026": "miramar-rosemary-beach-vacation-guide",
  "monterey-carmel-california-vacation-guide-2026": "monterey-carmel-california-vacation-guide",
  "napa-valley-wine-country-vacation-guide-2026": "napa-valley-wine-country-vacation-guide",
  "orange-beach-vacation-guide-2026": "orange-beach-vacation-guide",
  "outer-banks-vacation-guide-2026": "outer-banks-vacation-guide",
  "panama-city-beach-vacation-guide-2026": "panama-city-beach-vacation-guide",
  "san-diego-vacation-guide-2026": "san-diego-vacation-guide",
  "st-augustine-florida-vacation-guide-2026": "st-augustine-florida-vacation-guide",
  "ultimate-cruise-planning-guide-2026": "ultimate-cruise-planning-guide",
  "vail-ski-vacation-guide-2026": "vail-ski-vacation-guide",
};

// Non-default locales get an explicit prefix; the default locale is served bare
// (localePrefix: "as-needed"). Derived from routing so a new locale cannot ship
// pages without redirects. The ".ts" suffix is required by the Node strip-types
// loader that command-post/slug_guard.py uses to evaluate this module.
export const PREFIXED_LOCALES: readonly string[] = routing.locales.filter(
  (locale) => locale !== routing.defaultLocale,
);

export interface SlugRedirect {
  source: string;
  destination: string;
  permanent: boolean;
}

/**
 * Image URLs renamed in 8655f8b: the directory changed for all 24 renames, and
 * every basename that started with the old slug (hero + body-N) was prefix-swapped
 * to the new slug. Rule 1 handles those (`:tail` is one path segment, so it matches
 * `hero.png` and `body-10.png`); rule 2 catches every other basename. Rule 1 must
 * come first or `:path*` would send `<old>-hero.png` to `<new>/<old>-hero.png`.
 * Next.js evaluates redirects() before `public/` and before middleware, so the
 * `*.png` middleware exclusion does not matter here.
 */
export function buildImageRedirects(oldSlug: string, newSlug: string): SlugRedirect[] {
  return [
    {
      source: `/images/articles/${oldSlug}/${oldSlug}-:tail`,
      destination: `/images/articles/${newSlug}/${newSlug}-:tail`,
      permanent: true,
    },
    {
      source: `/images/articles/${oldSlug}/:path*`,
      destination: `/images/articles/${newSlug}/:path*`,
      permanent: true,
    },
  ];
}

/** Test helper: apply the two image rules to one URL the way Next would (first match wins). */
export function resolveImageRedirect(url: string): string | null {
  const match = /^\/images\/articles\/([^/]+)\/([^/]+)$/.exec(url);
  if (!match) return null;
  const [, oldSlug, basename] = match;
  const newSlug = SLUG_RENAMES[oldSlug];
  if (!newSlug) return null;
  if (basename.startsWith(`${oldSlug}-`)) {
    return `/images/articles/${newSlug}/${newSlug}-${basename.slice(oldSlug.length + 1)}`;
  }
  return `/images/articles/${newSlug}/${basename}`;
}

export function buildSlugRedirects(): SlugRedirect[] {
  return Object.entries(SLUG_RENAMES).flatMap(([oldSlug, newSlug]) => [
    { source: `/${oldSlug}/`, destination: `/${newSlug}/`, permanent: true },
    ...PREFIXED_LOCALES.map((locale) => ({
      source: `/${locale}/${oldSlug}/`,
      destination: `/${locale}/${newSlug}/`,
      permanent: true,
    })),
    ...buildImageRedirects(oldSlug, newSlug),
  ]);
}
