// GENERATED by scripts/rename_evergreen_slugs.py on 2026-09-01T19:40:21Z — do not hand-edit.
// Checked in deliberately: after the rename the old slugs no longer exist on disk,
// so this map cannot be re-derived. It is the source of truth for the 301/308s.
export const SLUG_RENAMES: Readonly<Record<string, string>> = {
  "asheville-north-carolina-vacation-guide-2026": "asheville-north-carolina-vacation-guide",
  "best-cruise-itineraries-fort-lauderdale-miami-2026": "best-cruise-itineraries-fort-lauderdale-miami",
  "big-sky-mt-vacation-guide-2026": "big-sky-mt-vacation-guide",
  "boston-weekend-getaway-guide-2026": "boston-weekend-getaway-guide",
  "cape-cod-vacation-guide-2026": "cape-cod-vacation-guide",
  "caribbean-cruise-itineraries-2026": "caribbean-cruise-itineraries",
  "charleston-coast-vacation-guide-2026": "charleston-coast-vacation-guide",
  "florida-travel-guide-2019": "florida-travel-guide",
  "fort-walton-beach-vacation-guide-2026": "fort-walton-beach-vacation-guide",
  "hawaii-vacation-planning-guide-2026": "hawaii-vacation-planning-guide",
  "hilton-head-vacation-guide-2026": "hilton-head-vacation-guide",
  "key-west-florida-vacation-guide-2026": "key-west-florida-vacation-guide",
  "lake-tahoe-vacation-guide-2026": "lake-tahoe-vacation-guide",
  "mexico-vacation-guide-2026": "mexico-vacation-guide",
  "miramar-rosemary-beach-vacation-guide-2026": "miramar-rosemary-beach-vacation-guide",
  "monterey-carmel-california-vacation-guide-2026": "monterey-carmel-california-vacation-guide",
  "napa-valley-wine-country-vacation-guide-2026": "napa-valley-wine-country-vacation-guide",
  "orange-beach-vacation-guide-2026": "orange-beach-vacation-guide",
  "outer-banks-vacation-guide-2026": "outer-banks-vacation-guide",
  "panama-city-beach-vacation-guide-2026": "panama-city-beach-vacation-guide",
  "san-diego-vacation-guide-2026": "san-diego-vacation-guide",
  "st-augustine-florida-vacation-guide-2026": "st-augustine-florida-vacation-guide",
  "ultimate-cruise-planning-guide-2026": "ultimate-cruise-planning-guide",
  "vail-ski-vacation-guide-2026": "vail-ski-vacation-guide",
};

// Non-default locales get an explicit prefix; `en` is served bare (localePrefix: "as-needed").
export const PREFIXED_LOCALES = ["es", "pt", "fr", "de", "it"] as const;

export interface SlugRedirect {
  source: string;
  destination: string;
  permanent: boolean;
}

export function buildSlugRedirects(): SlugRedirect[] {
  return Object.entries(SLUG_RENAMES).flatMap(([oldSlug, newSlug]) => [
    { source: `/${oldSlug}/`, destination: `/${newSlug}/`, permanent: true },
    ...PREFIXED_LOCALES.map((locale) => ({
      source: `/${locale}/${oldSlug}/`,
      destination: `/${locale}/${newSlug}/`,
      permanent: true,
    })),
  ]);
}
